# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5db9b2a44065ae0f0efdd95d6557c11b5f9bdf6e0b872a75b0f939ebe58eeb16c4204d1ff33e8f32dae6f95a2d00e21c6b6be4ae1f74d58bb19d93f5b1ee2c4c

test:
  secret_key_base: 35514bbd609a1586e7fed9093bc8a2a3b86c8f072e87ad2efca2e984bb95b94a1269ec76bfbeb9eff4a403da1333ce290de633b9f74f7d06768ce82cd329a036

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
